const express=require('express');const Database=require('better-sqlite3');const path=require('path');const crypto=require('crypto');
const app=express();app.use(express.json());
require('fs').mkdirSync(path.join(__dirname,'data'),{recursive:true});const db=new Database(path.join(__dirname,'data','competition.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS competitions(id TEXT PRIMARY KEY,name TEXT,questions INTEGER DEFAULT 20,minTable INTEGER DEFAULT 2,maxTable INTEGER DEFAULT 12,timeLimit INTEGER DEFAULT 300,open INTEGER DEFAULT 1,createdAt TEXT);CREATE TABLE IF NOT EXISTS students(id TEXT PRIMARY KEY,name TEXT,grade TEXT,className TEXT,teacher TEXT,createdAt TEXT);CREATE TABLE IF NOT EXISTS attempts(id TEXT PRIMARY KEY,competitionId TEXT,studentId TEXT,startTime TEXT,endTime TEXT,totalTime REAL,correct INTEGER,incorrect INTEGER,accuracy REAL,score REAL,completed INTEGER DEFAULT 0);CREATE TABLE IF NOT EXISTS answers(id INTEGER PRIMARY KEY AUTOINCREMENT,attemptId TEXT,qIndex INTEGER,a INTEGER,correctAnswer INTEGER,isCorrect INTEGER,timeSpent REAL);`);
const now=()=>new Date().toISOString();if(!db.prepare('SELECT 1 FROM competitions LIMIT 1').get())db.prepare('INSERT INTO competitions (id,name,questions,minTable,maxTable,timeLimit,open,createdAt) VALUES (?,?,?,?,?,?,?,?)').run('default','Multiplication Masters Challenge',20,2,12,300,1,now());
const comp=()=>db.prepare('SELECT * FROM competitions ORDER BY createdAt DESC LIMIT 1').get();
function qs(c){let arr=[];for(let i=0;i<c.questions;i++){const a=Math.floor(Math.random()*(c.maxTable-c.minTable+1))+c.minTable;const b=Math.floor(Math.random()*12)+1;arr.push({a,b,answer:a*b});}return arr;}
app.get('/api/competition',(req,res)=>res.json(comp()));
app.post('/api/register',(req,res)=>{const {id,name,grade,className='',teacher=''}=req.body;if(!id||!name||!grade)return res.status(400).json({error:'Student ID, name and grade are required'});const c=comp();if(!c.open)return res.status(403).json({error:'Registration is closed'});db.prepare(`INSERT INTO students(id,name,grade,className,teacher,createdAt) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,grade=excluded.grade,className=excluded.className,teacher=excluded.teacher`).run(id,name,grade,className,teacher,now());res.json({studentId:id,registrationCode:crypto.createHash('sha256').update(id+'|'+c.id).digest('hex').slice(0,10).toUpperCase()});});
app.post('/api/start',(req,res)=>{const {studentId}=req.body,c=comp(),s=db.prepare('SELECT * FROM students WHERE id=?').get(studentId);if(!s)return res.status(404).json({error:'Student not found'});const existing=db.prepare('SELECT id FROM attempts WHERE competitionId=? AND studentId=?').get(c.id,studentId);if(existing)return res.status(409).json({error:'This student already has an official attempt',attemptId:existing.id});const id=crypto.randomUUID(),start=now();db.prepare('INSERT INTO attempts(id,competitionId,studentId,startTime) VALUES(?,?,?,?)').run(id,c.id,studentId,start);res.json({attemptId:id,startTime:start,questions:qs(c).map(x=>({a:x.a,b:x.b})),timeLimit:c.timeLimit});});
app.post('/api/submit',(req,res)=>{const {attemptId,answers=[]}=req.body;const at=db.prepare('SELECT * FROM attempts WHERE id=?').get(attemptId);if(!at)return res.status(404).json({error:'Attempt not found'});if(at.completed)return res.status(409).json({error:'Already submitted'});const c=db.prepare('SELECT * FROM competitions WHERE id=?').get(at.competitionId);const started=new Date(at.startTime).getTime(),end=Date.now();const total=Math.min((end-started)/1000,c.timeLimit);let correct=0;const tx=db.transaction(()=>{db.prepare('DELETE FROM answers WHERE attemptId=?').run(attemptId);for(const x of answers){const ok=Number(x.answer)===Number(x.correctAnswer);if(ok)correct++;db.prepare('INSERT INTO answers(attemptId,qIndex,a,correctAnswer,isCorrect,timeSpent) VALUES(?,?,?,?,?,?)').run(attemptId,x.qIndex,Number(x.answer),Number(x.correctAnswer),ok?1:0,Number(x.timeSpent||0));}const n=c.questions,incorrect=n-correct,accuracy=correct/n*100,score=accuracy;db.prepare('UPDATE attempts SET endTime=?,totalTime=?,correct=?,incorrect=?,accuracy=?,score=?,completed=1 WHERE id=?').run(now(),total,correct,incorrect,accuracy,attemptId);});tx();res.json(resultFor(attemptId));});
function resultFor(id){const r=db.prepare(`SELECT a.*,s.name,s.grade,s.className FROM attempts a JOIN students s ON s.id=a.studentId WHERE a.id=?`).get(id);const rank=db.prepare(`SELECT COUNT(*)+1 rank FROM attempts WHERE competitionId=? AND completed=1 AND (score>? OR (score=? AND totalTime<?))`).get(r.competitionId,r.score,r.score,r.totalTime).rank;return {...r,rank};}
app.get('/api/results',(req,res)=>{const rows=db.prepare(`SELECT a.*,s.name,s.grade,s.className FROM attempts a JOIN students s ON s.id=a.studentId WHERE a.completed=1 ORDER BY a.score DESC,a.totalTime ASC`).all();res.json(rows.map((r,i)=>({...r,rank:i+1})));});
app.get('/api/students',(req,res)=>res.json(db.prepare('SELECT * FROM students ORDER BY name').all()));
app.post('/api/manage',(req,res)=>{const {action,...v}=req.body,c=comp();if(action==='config')db.prepare('UPDATE competitions SET name=?,questions=?,minTable=?,maxTable=?,timeLimit=? WHERE id=?').run(v.name,v.questions,v.minTable,v.maxTable,v.timeLimit,c.id);if(action==='open')db.prepare('UPDATE competitions SET open=? WHERE id=?').run(v.open?1:0,c.id);if(action==='reset'){db.prepare('DELETE FROM answers').run();db.prepare('DELETE FROM attempts').run();db.prepare('DELETE FROM students').run();}res.json(comp());});
app.get('/api/export',(req,res)=>{const rows=db.prepare(`SELECT a.id AS Attempt_ID,s.id AS Student_ID,s.name AS Student_Name,s.grade AS Grade,s.className AS Class,s.teacher AS Teacher,a.startTime AS Start_Time,a.endTime AS End_Time,a.totalTime AS Total_Time_Seconds,a.correct AS Total_Correct,a.incorrect AS Total_Incorrect,a.accuracy AS Accuracy_Percent,a.score AS Final_Score FROM attempts a JOIN students s ON s.id=a.studentId WHERE a.completed=1 ORDER BY a.score DESC,a.totalTime ASC`).all();res.json(rows);});
app.listen(process.env.PORT||3000,()=>console.log(`Multiplication Masters running on http://localhost:${process.env.PORT||3000}`));
